### ISSUE TITLE
Is it possible to use react-redux?

### ISSUE THREAD

**Issue by Kadrian** [iusehooks/redhooks#6]
Just a curious question: Is it possible to use `react-redux` instead of the own redhooks version of `connect`?

If not, then a performance comparison of `connect` might be interesting. The maintainers over here seem to have tuned it quite well.  https://github.com/reduxjs/react-redux/pull/1000

**Comment by iusehooks** [comment]
No you cannot use it, I agree that it would be nice to have a performance comparison. Would you like to write it?
