### ISSUE TITLE
problem with todomvc sample

### ISSUE THREAD

**Issue by eleach** [iusehooks/redhooks#7]
todomvc works on codesandbox. But when I download it, and do npm install, on npm start I get an error in components/MainSection - "Cannot read property 'completeAllTodos' of undefined".

When I do npm test, all the tests pass.

**Comment by antoniopangallo** [comment]
Hi Eleach, would you try to download it again.

The problem was that the: 

```
import * as actions from "./../actions"
```

imports all the modules as actions, but the actions were not spread properly into the connect().

That is the right way:

```
export default connect(
  mapStateToProps,
  { actions: { ...actions } }
)(MainSection); 
```

That was the wrong way:

```
export default connect(
  mapStateToProps,
  { actions }
)(MainSection);
```

Let me know if it works. Thanks

**Comment by eleach** [comment]
Hello Antonio, Thanks for the reply. It is now working. In addition, I got your basic example working (with a few corrections) on my computer and I also put that on codesandbox:  https://codesandbox.io/s/y0mnnp6q7v

One thing I notice is that in React dev tools it shows all the components rerendering on any change when i choose "highlight updates". Maybe I'm not interpreting this correctly. I'm mostly a beginner at all this. Thanks again for your help.

**Comment by eleach** [comment]
Hello Antonio, Thanks for the reply. It is now working. In addition, I got your basic example working (with a few corrections) on my computer and I also put that on codesandbox: 

    https://codesandbox.io/s/y0mnnp6q7v

One thing I notice is that in React dev tools it shows all the components rerendering on any change when i choose "highlight updates". Maybe I'm not interpreting this correctly. I'm mostly a beginner at all this. Thanks again for your help.

**Comment by iusehooks** [comment]
Hi Eleach, If you check the Profiler it gives you a better understanding on what it is re-render due to any action. In your example you are using the connect() only in one component, that means it will prevent only that component to get re-rendered.

**Comment by eleach** [comment]
I see. I will look more closely at the profiler. Thanks again for the responses.
